# -*- coding: utf-8 -*-
"""senai_python_aula2_FUNCAO_LINEAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uj9rYCwL7KMdo4S9Hjd56EJDf5glqix0
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([-2,-1,0,1,2])
y = 2 * x
print(y)

plt.plot(x,y)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Linear')
plt.legend(['y=2x'])
plt.show()

Ax=int(input("Insira Ax: "))
Ay=int(input("Insira Ay: "))
Bx=int(input("Insira Bx: "))
By=int(input("Insira By: "))
#Coeficiente Linear
a = (By-Ay)/(Bx-Ax)
#Coeficiente Angular
b = Ay-(a * Ax)
print('A lei de formação é: y=',a, 'x',b)
x=np.arange(-10, 10, 1, dtype=int)
y=a*x+b
#Plot
plt.plot(x, y)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Afim')
plt.show()

x = np.array([0,1,2,3])
y = np.array([3,8,1,10])
plt.subplot(1,2,1)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Serra')
plt.plot(x,y)

x = np.array([0,1,2,3])
y = np.array([10,20,30,40])
plt.subplot(1,2,2)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Linear')
plt.plot(x,y)
plt.tight_layout(pad=5.0)

x = np.array([-2,-1,0,1,2])
y1 = 2 * x + 6
print(y1)

y2 = 3 * x + 1
print(y2)

y3 = x - (1/5)
print(y3)

y4 = 2 * x
print(y4)

plt.subplot(2,2,1)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Serra')
plt.plot(x,y1)

plt.subplot(2,2,2)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Serra')
plt.plot(x,y2)

plt.subplot(2,2,3)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Serra')
plt.plot(x,y3)

plt.subplot(2,2,4)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Serra')
plt.plot(x,y4)